name: you_weather
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  dio: ^4.0.6
  geolocator: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/background/day.png
    - assets/climate_icons/01d.svg
    - assets/climate_icons/01n.svg
    - assets/climate_icons/02d.svg
    - assets/climate_icons/02d.svg
    - assets/climate_icons/03d.svg
    - assets/climate_icons/03d.svg
    - assets/climate_icons/04d.svg
    - assets/climate_icons/04d.svg
    - assets/climate_icons/09d.svg
    - assets/climate_icons/09d.svg
    - assets/climate_icons/10d.svg
    - assets/climate_icons/10d.svg
    - assets/climate_icons/11d.svg
    - assets/climate_icons/11d.svg
    - assets/climate_icons/13d.svg
    - assets/climate_icons/13d.svg
    - assets/climate_icons/50d.svg
    - assets/climate_icons/50d.svg
  